import type { NewsSource } from "../types";

const Time = {
  Realtime: 2 * 60 * 1000,
  Fast: 5 * 60 * 1000,
  Default: 10 * 60 * 1000,
  Common: 30 * 60 * 1000,
} as const;

export const newsSources = [
  {
    id: "weibo",
    name: "微博",
    title: "实时热搜",
    type: "hottest",
    color: "red",
    home: "https://weibo.com",
    intervalMs: Time.Realtime,
  },
  {
    id: "zhihu",
    name: "知乎",
    title: "热榜",
    type: "hottest",
    color: "blue",
    home: "https://www.zhihu.com",
    intervalMs: Time.Default,
  },
  {
    id: "baidu",
    name: "百度热搜",
    title: "热搜榜",
    type: "hottest",
    color: "blue",
    home: "https://top.baidu.com",
    intervalMs: Time.Default,
  },
  {
    id: "toutiao",
    name: "今日头条",
    title: "热榜",
    type: "hottest",
    color: "red",
    home: "https://www.toutiao.com",
    intervalMs: Time.Default,
  },
  {
    id: "douyin",
    name: "抖音",
    title: "热点榜",
    type: "hottest",
    color: "gray",
    home: "https://www.douyin.com",
    intervalMs: Time.Default,
  },
  {
    id: "bilibili-hot-search",
    name: "哔哩哔哩",
    title: "热搜",
    type: "hottest",
    color: "blue",
    home: "https://www.bilibili.com",
    intervalMs: Time.Default,
  },
  {
    id: "bilibili-hot-video",
    name: "哔哩哔哩",
    title: "热门视频",
    type: "hottest",
    color: "blue",
    home: "https://www.bilibili.com",
    intervalMs: Time.Common,
  },
  {
    id: "ithome",
    name: "IT之家",
    title: "最新",
    type: "realtime",
    color: "red",
    home: "https://www.ithome.com",
    intervalMs: Time.Fast,
  },
  {
    id: "36kr",
    name: "36氪",
    title: "快讯",
    type: "realtime",
    color: "blue",
    home: "https://36kr.com",
    intervalMs: Time.Fast,
  },
  {
    id: "wallstreetcn-quick",
    name: "华尔街见闻",
    title: "快讯",
    type: "realtime",
    color: "blue",
    home: "https://wallstreetcn.com",
    intervalMs: Time.Fast,
  },
  {
    id: "wallstreetcn-news",
    name: "华尔街见闻",
    title: "最新",
    type: "realtime",
    color: "blue",
    home: "https://wallstreetcn.com",
    intervalMs: Time.Common,
  },
  {
    id: "wallstreetcn-hot",
    name: "华尔街见闻",
    title: "最热",
    type: "hottest",
    color: "blue",
    home: "https://wallstreetcn.com",
    intervalMs: Time.Common,
  },
  {
    id: "jin10",
    name: "金十数据",
    title: "快讯",
    type: "realtime",
    color: "blue",
    home: "https://www.jin10.com",
    intervalMs: Time.Default,
  },
  {
    id: "cls-telegraph",
    name: "财联社",
    title: "电报",
    type: "realtime",
    color: "red",
    home: "https://www.cls.cn",
    intervalMs: Time.Fast,
  },
  {
    id: "cls-depth",
    name: "财联社",
    title: "深度",
    type: "realtime",
    color: "red",
    home: "https://www.cls.cn",
    intervalMs: Time.Default,
  },
  {
    id: "cls-hot",
    name: "财联社",
    title: "热门",
    type: "hottest",
    color: "red",
    home: "https://www.cls.cn",
    intervalMs: Time.Default,
  },
  {
    id: "v2ex",
    name: "V2EX",
    title: "最新分享",
    type: "realtime",
    color: "slate",
    home: "https://v2ex.com",
    intervalMs: Time.Common,
  },
  {
    id: "juejin",
    name: "稀土掘金",
    title: "热门文章",
    type: "hottest",
    color: "blue",
    home: "https://juejin.cn",
    intervalMs: Time.Common,
  },
  {
    id: "sspai",
    name: "少数派",
    title: "热门文章",
    type: "hottest",
    color: "red",
    home: "https://sspai.com",
    intervalMs: Time.Common,
  },
  {
    id: "hackernews",
    name: "Hacker News",
    title: "Top Stories",
    type: "hottest",
    color: "orange",
    home: "https://news.ycombinator.com",
    intervalMs: Time.Common,
  },
  {
    id: "solidot",
    name: "Solidot",
    title: "开源与科技",
    type: "realtime",
    color: "teal",
    home: "https://solidot.org",
    intervalMs: Time.Common,
  },
  {
    id: "github",
    name: "GitHub",
    title: "Trending",
    type: "hottest",
    color: "gray",
    home: "https://github.com/trending",
    intervalMs: Time.Common,
  },
  {
    id: "steam",
    name: "Steam",
    title: "在线人数",
    type: "hottest",
    color: "blue",
    home: "https://store.steampowered.com",
    intervalMs: Time.Default,
  },
  {
    id: "zaobao",
    name: "联合早报",
    title: "即时",
    type: "realtime",
    color: "red",
    home: "https://www.zaobao.com.sg",
    intervalMs: Time.Default,
  },
  {
    id: "coolapk",
    name: "酷安",
    title: "今日最热",
    type: "hottest",
    color: "green",
    home: "https://www.coolapk.com",
    intervalMs: Time.Default,
  },
  {
    id: "mktnews-flash",
    name: "MKTNews",
    title: "快讯",
    type: "realtime",
    color: "indigo",
    home: "https://www.mktnews.net",
    intervalMs: Time.Fast,
  },
  {
    id: "36kr-renqi",
    name: "36氪",
    title: "人气榜",
    type: "hottest",
    color: "blue",
    home: "https://36kr.com",
    intervalMs: Time.Common,
  },
  {
    id: "hupu",
    name: "虎扑",
    title: "主干道热帖",
    type: "hottest",
    color: "orange",
    home: "https://bbs.hupu.com",
    intervalMs: Time.Common,
  },
  {
    id: "tieba",
    name: "百度贴吧",
    title: "热议",
    type: "hottest",
    color: "blue",
    home: "https://tieba.baidu.com",
    intervalMs: Time.Common,
  },
  {
    id: "thepaper",
    name: "澎湃新闻",
    title: "热榜",
    type: "hottest",
    color: "slate",
    home: "https://www.thepaper.cn",
    intervalMs: Time.Default,
  },
  {
    id: "sputniknewscn",
    name: "卫星通讯社",
    title: "滚动",
    type: "realtime",
    color: "blue",
    home: "https://sputniknews.cn",
    intervalMs: Time.Default,
  },
  {
    id: "cankaoxiaoxi",
    name: "参考消息",
    title: "滚动",
    type: "realtime",
    color: "red",
    home: "https://www.cankaoxiaoxi.com",
    intervalMs: Time.Default,
  },
  {
    id: "pcbeta-windows11",
    name: "远景论坛",
    title: "Win11",
    type: "realtime",
    color: "blue",
    home: "https://bbs.pcbeta.com",
    intervalMs: Time.Common,
  },
  {
    id: "xueqiu-hotstock",
    name: "雪球",
    title: "热门股票",
    type: "hottest",
    color: "orange",
    home: "https://xueqiu.com",
    intervalMs: Time.Default,
  },
  {
    id: "gelonghui",
    name: "格隆汇",
    title: "事件",
    type: "realtime",
    color: "red",
    home: "https://www.gelonghui.com",
    intervalMs: Time.Default,
  },
  {
    id: "fastbull-express",
    name: "法布财经",
    title: "快讯",
    type: "realtime",
    color: "blue",
    home: "https://www.fastbull.com",
    intervalMs: Time.Fast,
  },
  {
    id: "fastbull-news",
    name: "法布财经",
    title: "头条",
    type: "realtime",
    color: "blue",
    home: "https://www.fastbull.com",
    intervalMs: Time.Default,
  },
  {
    id: "producthunt",
    name: "Product Hunt",
    title: "Today",
    type: "hottest",
    color: "orange",
    home: "https://www.producthunt.com",
    intervalMs: Time.Common,
  },
  {
    id: "bilibili-ranking",
    name: "哔哩哔哩",
    title: "排行榜",
    type: "hottest",
    color: "blue",
    home: "https://www.bilibili.com",
    intervalMs: Time.Common,
  },
  {
    id: "kuaishou",
    name: "快手",
    title: "热榜",
    type: "hottest",
    color: "orange",
    home: "https://www.kuaishou.com",
    intervalMs: Time.Default,
  },
  {
    id: "kaopu",
    name: "靠谱新闻",
    title: "聚合",
    type: "realtime",
    color: "slate",
    home: "https://kaopu.cc",
    intervalMs: Time.Default,
  },
  {
    id: "nowcoder",
    name: "牛客",
    title: "热榜",
    type: "hottest",
    color: "blue",
    home: "https://www.nowcoder.com",
    intervalMs: Time.Common,
  },
  {
    id: "ifeng",
    name: "凤凰网",
    title: "热点资讯",
    type: "hottest",
    color: "red",
    home: "https://www.ifeng.com",
    intervalMs: Time.Default,
  },
  {
    id: "chongbuluo-latest",
    name: "虫部落",
    title: "最新",
    type: "realtime",
    color: "green",
    home: "https://www.chongbuluo.com",
    intervalMs: Time.Common,
  },
  {
    id: "chongbuluo-hot",
    name: "虫部落",
    title: "最热",
    type: "hottest",
    color: "green",
    home: "https://www.chongbuluo.com",
    intervalMs: Time.Common,
  },
  {
    id: "douban",
    name: "豆瓣",
    title: "热门电影",
    type: "hottest",
    color: "green",
    home: "https://movie.douban.com",
    intervalMs: Time.Common,
  },
  {
    id: "tencent-hot",
    name: "腾讯新闻",
    title: "综合早报",
    type: "hottest",
    color: "blue",
    home: "https://news.qq.com",
    intervalMs: Time.Default,
  },
  {
    id: "freebuf",
    name: "Freebuf",
    title: "网络安全",
    type: "hottest",
    color: "slate",
    home: "https://www.freebuf.com",
    intervalMs: Time.Common,
  },
  {
    id: "qqvideo-tv-hotsearch",
    name: "腾讯视频",
    title: "热搜榜",
    type: "hottest",
    color: "blue",
    home: "https://v.qq.com",
    intervalMs: Time.Default,
  },
  {
    id: "iqiyi-hot-ranklist",
    name: "爱奇艺",
    title: "热播榜",
    type: "hottest",
    color: "green",
    home: "https://www.iqiyi.com",
    intervalMs: Time.Default,
  },
] satisfies NewsSource[];

export const newsSourceIds = newsSources.map((source) => source.id);

export const newsSourceMap = new Map(
  newsSources.map((source) => [source.id, source]),
);

export const isNewsSourceId = (value: string): value is string => {
  return newsSourceMap.has(value);
};

export const getNewsDirectory = () => ({
  sources: newsSources,
});
